version: "3.9"
services:
  assignmentservice.host:
    container_name: "assignment_service"
    build: 
      context: .
      dockerfile: ./src/AssignmentService.Host/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./seed:/seed
    networks:
      - local
  mongo: 
    image: "mongo"
    restart: on-failure
    container_name: "mongo"
    networks:
      - local
    ports: 
      - "27017:27017"
networks: 
  local: 
    driver: bridge